// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v3.21.12
// source: protocol/chord.proto

package protocol

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// The request message for Ping, containing no fields
type PingRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PingRequest) Reset() {
	*x = PingRequest{}
	mi := &file_protocol_chord_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PingRequest) ProtoMessage() {}

func (x *PingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_protocol_chord_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PingRequest.ProtoReflect.Descriptor instead.
func (*PingRequest) Descriptor() ([]byte, []int) {
	return file_protocol_chord_proto_rawDescGZIP(), []int{0}
}

// The response message for Ping, containing no fields
type PingResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PingResponse) Reset() {
	*x = PingResponse{}
	mi := &file_protocol_chord_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PingResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PingResponse) ProtoMessage() {}

func (x *PingResponse) ProtoReflect() protoreflect.Message {
	mi := &file_protocol_chord_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PingResponse.ProtoReflect.Descriptor instead.
func (*PingResponse) Descriptor() ([]byte, []int) {
	return file_protocol_chord_proto_rawDescGZIP(), []int{1}
}

// The request message for Put
type PutRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Value         string                 `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	IsReplica     bool                   `protobuf:"varint,3,opt,name=is_replica,json=isReplica,proto3" json:"is_replica,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PutRequest) Reset() {
	*x = PutRequest{}
	mi := &file_protocol_chord_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PutRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PutRequest) ProtoMessage() {}

func (x *PutRequest) ProtoReflect() protoreflect.Message {
	mi := &file_protocol_chord_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PutRequest.ProtoReflect.Descriptor instead.
func (*PutRequest) Descriptor() ([]byte, []int) {
	return file_protocol_chord_proto_rawDescGZIP(), []int{2}
}

func (x *PutRequest) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *PutRequest) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

func (x *PutRequest) GetIsReplica() bool {
	if x != nil {
		return x.IsReplica
	}
	return false
}

// The response message for Put
type PutResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PutResponse) Reset() {
	*x = PutResponse{}
	mi := &file_protocol_chord_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PutResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PutResponse) ProtoMessage() {}

func (x *PutResponse) ProtoReflect() protoreflect.Message {
	mi := &file_protocol_chord_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PutResponse.ProtoReflect.Descriptor instead.
func (*PutResponse) Descriptor() ([]byte, []int) {
	return file_protocol_chord_proto_rawDescGZIP(), []int{3}
}

// The request message for Get
type GetRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRequest) Reset() {
	*x = GetRequest{}
	mi := &file_protocol_chord_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRequest) ProtoMessage() {}

func (x *GetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_protocol_chord_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRequest.ProtoReflect.Descriptor instead.
func (*GetRequest) Descriptor() ([]byte, []int) {
	return file_protocol_chord_proto_rawDescGZIP(), []int{4}
}

func (x *GetRequest) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

// The response message for Get
type GetResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Value         string                 `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetResponse) Reset() {
	*x = GetResponse{}
	mi := &file_protocol_chord_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetResponse) ProtoMessage() {}

func (x *GetResponse) ProtoReflect() protoreflect.Message {
	mi := &file_protocol_chord_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetResponse.ProtoReflect.Descriptor instead.
func (*GetResponse) Descriptor() ([]byte, []int) {
	return file_protocol_chord_proto_rawDescGZIP(), []int{5}
}

func (x *GetResponse) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

// The request message for Delete
type DeleteRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteRequest) Reset() {
	*x = DeleteRequest{}
	mi := &file_protocol_chord_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteRequest) ProtoMessage() {}

func (x *DeleteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_protocol_chord_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteRequest.ProtoReflect.Descriptor instead.
func (*DeleteRequest) Descriptor() ([]byte, []int) {
	return file_protocol_chord_proto_rawDescGZIP(), []int{6}
}

func (x *DeleteRequest) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

// The response message for Delete
type DeleteResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteResponse) Reset() {
	*x = DeleteResponse{}
	mi := &file_protocol_chord_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteResponse) ProtoMessage() {}

func (x *DeleteResponse) ProtoReflect() protoreflect.Message {
	mi := &file_protocol_chord_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteResponse.ProtoReflect.Descriptor instead.
func (*DeleteResponse) Descriptor() ([]byte, []int) {
	return file_protocol_chord_proto_rawDescGZIP(), []int{7}
}

// The request message for GetAll
type GetAllRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAllRequest) Reset() {
	*x = GetAllRequest{}
	mi := &file_protocol_chord_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAllRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAllRequest) ProtoMessage() {}

func (x *GetAllRequest) ProtoReflect() protoreflect.Message {
	mi := &file_protocol_chord_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAllRequest.ProtoReflect.Descriptor instead.
func (*GetAllRequest) Descriptor() ([]byte, []int) {
	return file_protocol_chord_proto_rawDescGZIP(), []int{8}
}

// The response message for GetAll
type GetAllResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	KeyValues     map[string]string      `protobuf:"bytes,1,rep,name=key_values,json=keyValues,proto3" json:"key_values,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAllResponse) Reset() {
	*x = GetAllResponse{}
	mi := &file_protocol_chord_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAllResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAllResponse) ProtoMessage() {}

func (x *GetAllResponse) ProtoReflect() protoreflect.Message {
	mi := &file_protocol_chord_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAllResponse.ProtoReflect.Descriptor instead.
func (*GetAllResponse) Descriptor() ([]byte, []int) {
	return file_protocol_chord_proto_rawDescGZIP(), []int{9}
}

func (x *GetAllResponse) GetKeyValues() map[string]string {
	if x != nil {
		return x.KeyValues
	}
	return nil
}

// The request message for FindClosestPreceding
type FindClosestPrecedingRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FindClosestPrecedingRequest) Reset() {
	*x = FindClosestPrecedingRequest{}
	mi := &file_protocol_chord_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FindClosestPrecedingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FindClosestPrecedingRequest) ProtoMessage() {}

func (x *FindClosestPrecedingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_protocol_chord_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FindClosestPrecedingRequest.ProtoReflect.Descriptor instead.
func (*FindClosestPrecedingRequest) Descriptor() ([]byte, []int) {
	return file_protocol_chord_proto_rawDescGZIP(), []int{10}
}

func (x *FindClosestPrecedingRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type FindClosestPrecedingResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Address       string                 `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FindClosestPrecedingResponse) Reset() {
	*x = FindClosestPrecedingResponse{}
	mi := &file_protocol_chord_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FindClosestPrecedingResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FindClosestPrecedingResponse) ProtoMessage() {}

func (x *FindClosestPrecedingResponse) ProtoReflect() protoreflect.Message {
	mi := &file_protocol_chord_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FindClosestPrecedingResponse.ProtoReflect.Descriptor instead.
func (*FindClosestPrecedingResponse) Descriptor() ([]byte, []int) {
	return file_protocol_chord_proto_rawDescGZIP(), []int{11}
}

func (x *FindClosestPrecedingResponse) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

// The request message for FindSuccessor
type FindSuccessorRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FindSuccessorRequest) Reset() {
	*x = FindSuccessorRequest{}
	mi := &file_protocol_chord_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FindSuccessorRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FindSuccessorRequest) ProtoMessage() {}

func (x *FindSuccessorRequest) ProtoReflect() protoreflect.Message {
	mi := &file_protocol_chord_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FindSuccessorRequest.ProtoReflect.Descriptor instead.
func (*FindSuccessorRequest) Descriptor() ([]byte, []int) {
	return file_protocol_chord_proto_rawDescGZIP(), []int{12}
}

func (x *FindSuccessorRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type FindSuccessorResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Address       string                 `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FindSuccessorResponse) Reset() {
	*x = FindSuccessorResponse{}
	mi := &file_protocol_chord_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FindSuccessorResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FindSuccessorResponse) ProtoMessage() {}

func (x *FindSuccessorResponse) ProtoReflect() protoreflect.Message {
	mi := &file_protocol_chord_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FindSuccessorResponse.ProtoReflect.Descriptor instead.
func (*FindSuccessorResponse) Descriptor() ([]byte, []int) {
	return file_protocol_chord_proto_rawDescGZIP(), []int{13}
}

func (x *FindSuccessorResponse) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

// message for get list of Successors
type GetSuccessorListRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSuccessorListRequest) Reset() {
	*x = GetSuccessorListRequest{}
	mi := &file_protocol_chord_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSuccessorListRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSuccessorListRequest) ProtoMessage() {}

func (x *GetSuccessorListRequest) ProtoReflect() protoreflect.Message {
	mi := &file_protocol_chord_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSuccessorListRequest.ProtoReflect.Descriptor instead.
func (*GetSuccessorListRequest) Descriptor() ([]byte, []int) {
	return file_protocol_chord_proto_rawDescGZIP(), []int{14}
}

type GetSuccessorListResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Successors    []string               `protobuf:"bytes,1,rep,name=successors,proto3" json:"successors,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSuccessorListResponse) Reset() {
	*x = GetSuccessorListResponse{}
	mi := &file_protocol_chord_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSuccessorListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSuccessorListResponse) ProtoMessage() {}

func (x *GetSuccessorListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_protocol_chord_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSuccessorListResponse.ProtoReflect.Descriptor instead.
func (*GetSuccessorListResponse) Descriptor() ([]byte, []int) {
	return file_protocol_chord_proto_rawDescGZIP(), []int{15}
}

func (x *GetSuccessorListResponse) GetSuccessors() []string {
	if x != nil {
		return x.Successors
	}
	return nil
}

type NotifyRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Address       string                 `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NotifyRequest) Reset() {
	*x = NotifyRequest{}
	mi := &file_protocol_chord_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NotifyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NotifyRequest) ProtoMessage() {}

func (x *NotifyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_protocol_chord_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NotifyRequest.ProtoReflect.Descriptor instead.
func (*NotifyRequest) Descriptor() ([]byte, []int) {
	return file_protocol_chord_proto_rawDescGZIP(), []int{16}
}

func (x *NotifyRequest) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

type NotifyResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NotifyResponse) Reset() {
	*x = NotifyResponse{}
	mi := &file_protocol_chord_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NotifyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NotifyResponse) ProtoMessage() {}

func (x *NotifyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_protocol_chord_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NotifyResponse.ProtoReflect.Descriptor instead.
func (*NotifyResponse) Descriptor() ([]byte, []int) {
	return file_protocol_chord_proto_rawDescGZIP(), []int{17}
}

// message for get precedessor
type GetPredecessorRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPredecessorRequest) Reset() {
	*x = GetPredecessorRequest{}
	mi := &file_protocol_chord_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPredecessorRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPredecessorRequest) ProtoMessage() {}

func (x *GetPredecessorRequest) ProtoReflect() protoreflect.Message {
	mi := &file_protocol_chord_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPredecessorRequest.ProtoReflect.Descriptor instead.
func (*GetPredecessorRequest) Descriptor() ([]byte, []int) {
	return file_protocol_chord_proto_rawDescGZIP(), []int{18}
}

type GetPredecessorResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Address       string                 `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPredecessorResponse) Reset() {
	*x = GetPredecessorResponse{}
	mi := &file_protocol_chord_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPredecessorResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPredecessorResponse) ProtoMessage() {}

func (x *GetPredecessorResponse) ProtoReflect() protoreflect.Message {
	mi := &file_protocol_chord_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPredecessorResponse.ProtoReflect.Descriptor instead.
func (*GetPredecessorResponse) Descriptor() ([]byte, []int) {
	return file_protocol_chord_proto_rawDescGZIP(), []int{19}
}

func (x *GetPredecessorResponse) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

var File_protocol_chord_proto protoreflect.FileDescriptor

const file_protocol_chord_proto_rawDesc = "" +
	"\n" +
	"\x14protocol/chord.proto\x12\x05chord\"\r\n" +
	"\vPingRequest\"\x0e\n" +
	"\fPingResponse\"S\n" +
	"\n" +
	"PutRequest\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value\x12\x1d\n" +
	"\n" +
	"is_replica\x18\x03 \x01(\bR\tisReplica\"\r\n" +
	"\vPutResponse\"\x1e\n" +
	"\n" +
	"GetRequest\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\"#\n" +
	"\vGetResponse\x12\x14\n" +
	"\x05value\x18\x01 \x01(\tR\x05value\"!\n" +
	"\rDeleteRequest\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\"\x10\n" +
	"\x0eDeleteResponse\"\x0f\n" +
	"\rGetAllRequest\"\x93\x01\n" +
	"\x0eGetAllResponse\x12C\n" +
	"\n" +
	"key_values\x18\x01 \x03(\v2$.chord.GetAllResponse.KeyValuesEntryR\tkeyValues\x1a<\n" +
	"\x0eKeyValuesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"-\n" +
	"\x1bFindClosestPrecedingRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"8\n" +
	"\x1cFindClosestPrecedingResponse\x12\x18\n" +
	"\aaddress\x18\x01 \x01(\tR\aaddress\"&\n" +
	"\x14FindSuccessorRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"1\n" +
	"\x15FindSuccessorResponse\x12\x18\n" +
	"\aaddress\x18\x01 \x01(\tR\aaddress\"\x19\n" +
	"\x17GetSuccessorListRequest\":\n" +
	"\x18GetSuccessorListResponse\x12\x1e\n" +
	"\n" +
	"successors\x18\x01 \x03(\tR\n" +
	"successors\")\n" +
	"\rNotifyRequest\x12\x18\n" +
	"\aaddress\x18\x01 \x01(\tR\aaddress\"\x10\n" +
	"\x0eNotifyResponse\"\x17\n" +
	"\x15GetPredecessorRequest\"2\n" +
	"\x16GetPredecessorResponse\x12\x18\n" +
	"\aaddress\x18\x01 \x01(\tR\aaddress2\x9e\x05\n" +
	"\x05Chord\x121\n" +
	"\x04Ping\x12\x12.chord.PingRequest\x1a\x13.chord.PingResponse\"\x00\x12.\n" +
	"\x03Put\x12\x11.chord.PutRequest\x1a\x12.chord.PutResponse\"\x00\x12.\n" +
	"\x03Get\x12\x11.chord.GetRequest\x1a\x12.chord.GetResponse\"\x00\x127\n" +
	"\x06Delete\x12\x14.chord.DeleteRequest\x1a\x15.chord.DeleteResponse\"\x00\x127\n" +
	"\x06GetAll\x12\x14.chord.GetAllRequest\x1a\x15.chord.GetAllResponse\"\x00\x12a\n" +
	"\x14FindClosestPreceding\x12\".chord.FindClosestPrecedingRequest\x1a#.chord.FindClosestPrecedingResponse\"\x00\x12L\n" +
	"\rFindSuccessor\x12\x1b.chord.FindSuccessorRequest\x1a\x1c.chord.FindSuccessorResponse\"\x00\x12U\n" +
	"\x10GetSuccessorList\x12\x1e.chord.GetSuccessorListRequest\x1a\x1f.chord.GetSuccessorListResponse\"\x00\x127\n" +
	"\x06Notify\x12\x14.chord.NotifyRequest\x1a\x15.chord.NotifyResponse\"\x00\x12O\n" +
	"\x0eGetPredecessor\x12\x1c.chord.GetPredecessorRequest\x1a\x1d.chord.GetPredecessorResponse\"\x00B\x10Z\x0echord/protocolb\x06proto3"

var (
	file_protocol_chord_proto_rawDescOnce sync.Once
	file_protocol_chord_proto_rawDescData []byte
)

func file_protocol_chord_proto_rawDescGZIP() []byte {
	file_protocol_chord_proto_rawDescOnce.Do(func() {
		file_protocol_chord_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_protocol_chord_proto_rawDesc), len(file_protocol_chord_proto_rawDesc)))
	})
	return file_protocol_chord_proto_rawDescData
}

var file_protocol_chord_proto_msgTypes = make([]protoimpl.MessageInfo, 21)
var file_protocol_chord_proto_goTypes = []any{
	(*PingRequest)(nil),                  // 0: chord.PingRequest
	(*PingResponse)(nil),                 // 1: chord.PingResponse
	(*PutRequest)(nil),                   // 2: chord.PutRequest
	(*PutResponse)(nil),                  // 3: chord.PutResponse
	(*GetRequest)(nil),                   // 4: chord.GetRequest
	(*GetResponse)(nil),                  // 5: chord.GetResponse
	(*DeleteRequest)(nil),                // 6: chord.DeleteRequest
	(*DeleteResponse)(nil),               // 7: chord.DeleteResponse
	(*GetAllRequest)(nil),                // 8: chord.GetAllRequest
	(*GetAllResponse)(nil),               // 9: chord.GetAllResponse
	(*FindClosestPrecedingRequest)(nil),  // 10: chord.FindClosestPrecedingRequest
	(*FindClosestPrecedingResponse)(nil), // 11: chord.FindClosestPrecedingResponse
	(*FindSuccessorRequest)(nil),         // 12: chord.FindSuccessorRequest
	(*FindSuccessorResponse)(nil),        // 13: chord.FindSuccessorResponse
	(*GetSuccessorListRequest)(nil),      // 14: chord.GetSuccessorListRequest
	(*GetSuccessorListResponse)(nil),     // 15: chord.GetSuccessorListResponse
	(*NotifyRequest)(nil),                // 16: chord.NotifyRequest
	(*NotifyResponse)(nil),               // 17: chord.NotifyResponse
	(*GetPredecessorRequest)(nil),        // 18: chord.GetPredecessorRequest
	(*GetPredecessorResponse)(nil),       // 19: chord.GetPredecessorResponse
	nil,                                  // 20: chord.GetAllResponse.KeyValuesEntry
}
var file_protocol_chord_proto_depIdxs = []int32{
	20, // 0: chord.GetAllResponse.key_values:type_name -> chord.GetAllResponse.KeyValuesEntry
	0,  // 1: chord.Chord.Ping:input_type -> chord.PingRequest
	2,  // 2: chord.Chord.Put:input_type -> chord.PutRequest
	4,  // 3: chord.Chord.Get:input_type -> chord.GetRequest
	6,  // 4: chord.Chord.Delete:input_type -> chord.DeleteRequest
	8,  // 5: chord.Chord.GetAll:input_type -> chord.GetAllRequest
	10, // 6: chord.Chord.FindClosestPreceding:input_type -> chord.FindClosestPrecedingRequest
	12, // 7: chord.Chord.FindSuccessor:input_type -> chord.FindSuccessorRequest
	14, // 8: chord.Chord.GetSuccessorList:input_type -> chord.GetSuccessorListRequest
	16, // 9: chord.Chord.Notify:input_type -> chord.NotifyRequest
	18, // 10: chord.Chord.GetPredecessor:input_type -> chord.GetPredecessorRequest
	1,  // 11: chord.Chord.Ping:output_type -> chord.PingResponse
	3,  // 12: chord.Chord.Put:output_type -> chord.PutResponse
	5,  // 13: chord.Chord.Get:output_type -> chord.GetResponse
	7,  // 14: chord.Chord.Delete:output_type -> chord.DeleteResponse
	9,  // 15: chord.Chord.GetAll:output_type -> chord.GetAllResponse
	11, // 16: chord.Chord.FindClosestPreceding:output_type -> chord.FindClosestPrecedingResponse
	13, // 17: chord.Chord.FindSuccessor:output_type -> chord.FindSuccessorResponse
	15, // 18: chord.Chord.GetSuccessorList:output_type -> chord.GetSuccessorListResponse
	17, // 19: chord.Chord.Notify:output_type -> chord.NotifyResponse
	19, // 20: chord.Chord.GetPredecessor:output_type -> chord.GetPredecessorResponse
	11, // [11:21] is the sub-list for method output_type
	1,  // [1:11] is the sub-list for method input_type
	1,  // [1:1] is the sub-list for extension type_name
	1,  // [1:1] is the sub-list for extension extendee
	0,  // [0:1] is the sub-list for field type_name
}

func init() { file_protocol_chord_proto_init() }
func file_protocol_chord_proto_init() {
	if File_protocol_chord_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_protocol_chord_proto_rawDesc), len(file_protocol_chord_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   21,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_protocol_chord_proto_goTypes,
		DependencyIndexes: file_protocol_chord_proto_depIdxs,
		MessageInfos:      file_protocol_chord_proto_msgTypes,
	}.Build()
	File_protocol_chord_proto = out.File
	file_protocol_chord_proto_goTypes = nil
	file_protocol_chord_proto_depIdxs = nil
}
